# $Id$

CPSMAILBOXER_BOXES = {
    'boxertitle': {'type': 'Base Box',
              'title': 'titre',
              'provider': 'nuxeo',
              'btype': 'folder_header',
              'box_skin': 'here/box_lib/macros/mmcbox',
              'minimized': 0,
              'closed': 0,
              'slot': 'center',
              'order': 0,
              'display_in_subfolder': 0,
              'display_only_in_subfolder': 0,
              'locked': 0,
             },
    'content': {'type': 'Content Box',
                'title': 'Contenu du CPSMailBoxerFolder',
                'provider': 'nuxeo',
                'btype': 'default',
                'box_skin': 'here/box_lib/macros/wbox2',
                'minimized': 0,
                'closed': 0,
                'slot': 'center',
                'order': 1,
                'display_in_subfolder': 0,
                'display_only_in_subfolder': 0,
                'locked': 0,
                'folder': '',
                'nb_items': 0,
                'sort_by': None,
                'direction': None,
                'display': None,
                'zoom': 0,
                'query_title': '',
                'query_description': '',
                'query_fulltext': '',
                'query_status': '',
                'query_portal_type': [''],
                'query_modified': '',
               },
    'archive': {'type': 'Base Box',
                 'title': 'archive view',
                 'provider': 'cpsmailboxer',
                 'btype': 'archive',
                 'box_skin': 'here/box_lib/macros/wbox2',
                 'minimized': 0,
                 'closed': 0,
                 'slot': 'center',
                 'order': 2,
                 'display_in_subfolder': 0,
                 'display_only_in_subfolder': 0,
                 'locked': 0,
                 },
    'search': {'type': 'Base Box',
               'title': 'Search in mailbox archive',
               'provider': 'cpsmailboxer',
               'btype': 'search',
               'box_skin': 'here/box_lib/macros/wbox2',
               'minimized': 0,
               'closed': 0,
               'slot': 'center',
               'order': 1,
               'display_in_subfolder': 0,
               'display_only_in_subfolder': 0,
               'locked': 0,
              },
    }
